language: cpp

addons:
  apt:
    sources:
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3

    packages:
    - cmake
    - cmake-data
    - qt4-dev-tools
env:
  global:
    - NUM_THREADS=4

    - SCRIPTS=${TRAVIS_BUILD_DIR}/travis
    - EXTERNALS_DIR=/home/travis/external
    - PV_VERSION=5.0

    - PV_SOURCE_DIR=$EXTERNALS_DIR/pv-$PV_VERSION
    - PV_DIR=$EXTERNALS_DIR/pv-$PV_VERSION-build

before_install:


install:
  - $SCRIPTS/travis_build_pv.sh
  - $SCRIPTS/travis_before_script_cleanup.sh

cache:
  directories:
  - /home/travis/external/pv-5.0
  - /home/travis/external/pv-5.0-build

before_script:

  - mkdir build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH=$PV_DIR ..

script:
  - make -j$NUM_THREADS

after_success:


