language: cpp

matrix:
  include:
    - os: linux
      env: QT_BASE=55 COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: QT_BASE=55 COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: QT_BASE=55 COMPILER=g++-5 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

env:
  global:
    - NUM_THREADS=4

    - SCRIPTS=${TRAVIS_BUILD_DIR}/travis
    - EXTERNALS_DIR=/home/travis/external
    - PV_VERSION=5.0
    - PV_SOURCE_DIR=$EXTERNALS_DIR/pv-$PV_VERSION
    - PV_DIR=$EXTERNALS_DIR/pv-$PV_VERSION-build

before_install:
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
  - sudo apt-get update -qq


install:
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools ; source /opt/qt55/bin/qt55-env.sh ; export QTHOME=/opt/qt55 ; fi

  # cmake
  - curl -O https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
  - tar -xf cmake-3.4.1-Linux-x86_64.tar.gz
  - rm -f cmake-3.4.1-Linux-x86_64.tar.gz
  - export PATH=${PWD}/cmake-3.4.1-Linux-x86_64/bin:${PATH}

  - $SCRIPTS/travis_build_pv.sh
  - $SCRIPTS/travis_before_script_cleanup.sh


cache:
  directories:
  - /home/travis/external/pv-5.0
  - /home/travis/external/pv-5.0-build

before_script:

  - mkdir build
  - cd build


script:

after_success:


